name: Deploy to Nekoweb and GH Pages (Backup host)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nekoweb
      url: 'https://jbcarreon123.nekoweb.org/jbsite5/'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies (using Bun)
        continue-on-error: true
        run: bun install
      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Build jbsite
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NEKOWEB_APIKEY: '${{ secrets.NEKOWEB_APIKEY }}'
          NEKOWEB_COOKIE: '${{ secrets.NEKOWEB_COOKIE }}'
          COMMIT_HASH: '<a href="https://github.com/jbcarreon123/jbcarreon123.github.io/commit/${{ steps.commit.outputs.hash }}">${{ steps.commit.outputs.short }}</a>'
        run: bun run build
